docs:
  - "*.md"
  - .github/PULL_REQUEST_TEMPLATE/*.md
  - .github/pull_request_template.md
  - docs/**

icons:
  - svgs/*
  - app/assets/appfilter.xml

code:
  - ['app/**/*', '!app/assets/*', '!app/src/main/res/*/strings.xml']

locale:
  - app/src/main/res/*/strings.xml
  